<?php

return [
    [
        'name' => 'version',
        'title' => 'API版本(请勿修改该值)',
        'type' => 'radio',
        'content' => [],
        'value' => 'v2',
        'rule' => '',
        'msg' => '',
        'tip' => 'V2版本只支持微信支付V2密钥，V3版本只支持微信支付V3密钥，请勿修改该值！！！',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat',
        'title' => '微信',
        'type' => 'array',
        'content' => [],
        'value' => [
            'appid' => '',
            'app_id' => '',
            'app_secret' => '',
            'miniapp_id' => '',
            'mch_id' => '',
            'key' => '',
            'key_v3' => '',
            'mode' => 'normal',
            'sub_mch_id' => '',
            'sub_appid' => '',
            'sub_app_id' => '',
            'sub_miniapp_id' => '',
            'notify_url' => '',
            'cert_client' => '/addons/epay/certs/apiclient_cert.pem',
            'cert_key' => '/addons/epay/certs/apiclient_key.pem',
            'log' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '微信参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alipay',
        'title' => '支付宝',
        'type' => 'array',
        'content' => [],
        'value' => [
            'mode' => 'normal',
            'pid' => '',
            'app_id' => '2021004131657059',
            'notify_url' => '/addons/epay/api/notifyx/type/alipay',
            'return_url' => '/addons/epay/api/returnx/type/alipay',
            'private_key' => 'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjmYrKImt4OEJXZ/zOTurhgM4+tlvP2B9Z0iYAS4+XPR7rbxFk19cRWLlo4xCbLOdfpJbaHvu/VPSigGWsU4kztND0UB5cNihW7l1gGCboXtf+xnuY6WFiskDsdLgOXuPMycxtamR/GMpFSAhMSfYiIbNw01ESocBz/Bcd22QkvlDbwM4RRI0zohR1xhJb2qkO8hzt70ftgqSoggycbZj082ziq6YbkkkeYrjoXHN2hcAAA8zW3/mxwbsjjTf1G6CIWKqt6rVjpIIPn0CJiodj+L+rB4uaT47zVaZcQEQ+2aRfuegg+Mod15iPjVrKN+BpAUGLT3EBiAZx+9KMIAcvAgMBAAECggEAD24KXbfFp2nQ/ZH8LpRlEhKkaNX+FXImdfVsRBrbSjqHjRiDil2jo/Zq43R5XLvHl9FVtMXi9U6yIw4nVm53X70DaXzBAildxL72L5yTjq9XX1tfZ7dytbk185HaJIdEVE7eABD1bTRmChpfDaT5/chhHOYGmgfDP1m4y3pjKKZppARCtgND4X58CbCCWJE/m+kM51EVZv+ZjzuHjKzdCkOVGrWXSIPvkQm+SWLCfosSFwhsl9+JUMff5ys4c08WxA2n/cPW1fJmCKnsMtGGetderhxvdUVrjHQWFIxCEaOKouUhd76mjiKA31NWgdEXY2tq87FNvVNi869bXmNTyQKBgQDzZ08Or0a4yxsqZ+Eqc1cm0MIUKxXBmMwNIbkHl+wlxLJ51pvGuHCiN6mUj9JkxzBCDyIksQp8uTYFQZbBlGF/S9Tsfzgq8ErM0fqu7W7ZTUb+KmoOd9aDXyorXDDkRpoDcqG5X1NKfRevuC7SSjcde4JQ7brdA412d/IXI7LeXQKBgQDvYNwR4IYL6LUmxj4Y/rhkgKRDDNU4MfgSfpkmp7c5gTrSEohpUgGNuS/CnfeY889gbybvoq+t7bPU0kiIjgq77zk9Q9pvnNKJGev3YR9ZtrXRFuDP8x4EnTytfs1AK405pfLh5nVBH7zptyX2FPhz2GsnwBRLPbKjY92mkIvq+wKBgQDukWR4hS1xNInEz5pvjCtwvQ5szCn/3e6qNFJx8eMgxaEVMFbwuJiVNq99EFZsNpvDM6gIhIo94x7imf3UcMX7Ce2Be9Qmqez2whzN1aRfUpHxzsqysZzMmLrxUuQM6nJMTM/crGUrzl4n+gPSU7GfsQ3ymoAb3j6KTlg3e+L2dQKBgC7lM9fQu5IDsdF5ztqItEkEJqn4DqFmsKm24XwAKVX7qjFTbiPr69/+4otm9QWi5gKHZAJYRcB2K9/KnmkaIqI0uGr3KwjomRpA2Mhq34Bs2euvZrV2dHAE+cknaUBkB9O+XfnBc0Eh3ZmPxsER1KalREDSUWd4G9IEk3y5HqAXAoGBAJsMFDbLvImkXH/yvZioIN1JibhCVSbTtT67KHrwGgLS6ijG93Jf66NaGA/ukL9KhrYmyx8Ki+0OmuxckGqmg8HZg3fjgGYZRWOQgyJlMfsMXtBQ0uZV2SPZIjKec9UcYisw2qEHvR1Ry3LMbu6vkyUnDI6kKO2fCnMzP5x+qVdG',
            'signtype' => 'cert',
            'ali_public_key' => '/addons/epay/certs/alipayCertPublicKey.crt',
            'app_cert_public_key' => '/addons/epay/certs/appCertPublicKey.crt',
            'alipay_root_cert' => '/addons/epay/certs/alipayRootCert.crt',
            'log' => '1',
            'scanpay' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '支付宝参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wodpay',
        'title' => '个人支付宝',
        'type' => 'array',
        'content' => [],
        'value' => [
            'notify_url' => '/addons/epay/api/notifywod/paytype/wodpay',
            'return_url' => '/addons/epay/api/returnwod/paytype/wodpay',
            'uid' => '153734764515UYb37hy3rTmx4k7f640tI5',
            'secret' => 'ae1135053f4c3de46298528cccf7f41011599daf',
            'log' => '0',
            'scanpay' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '个人支付宝参数配置',
        'ok' => '',
        'extend' => '',
    ],
];
